### ISSUE TITLE
Add full error messages to parsing failures

### ISSUE THREAD

**Issue by jthom-ut** [nevinera/quiet_quality#115]
We hit this line in a project https://github.com/nevinera/quiet_quality/blob/main/lib/quiet_quality/tools/brakeman/parser.rb#L27, and it took a few extra steps to figure out what actually caused the parsing error. 

Would it be worth it to add the full error to the output? Or an option to see the full error?

**Comment by nevinera** [comment]
Oh, absolutely! I think the problem was that there could be an arbitrary number of them, and their output can be large. But probably the _first_ encountered error (truncated) would be better than nothing. Can you share a redacted form of the json output you encountered?

**Comment by nevinera** [comment]
(The other thing that might have been useful to you is `qq -Xbrakeman -v` - that should execute brakeman with mostly the same flags/targets as qq normally uses, but instead of capturing the json output and parsing it, it `exec`s the tool without the json flag - you'd have seen the normal brakeman error messages on stderr then. Though in brakeman's case that's literally just [`brakeman`](https://github.com/nevinera/quiet_quality/blob/main/lib/quiet_quality/tools/brakeman/runner.rb#L14), so it might not have been _that_ helpful to know)

**Comment by nevinera** [comment]
I think the simplest thing is actually to just _log_ the errors here at the `warn` level (which is visible by default). That _could_ produce a lot of output, but .. if so, your project has something seriously wrong (like the wrong ruby version or something).
